version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://noyon:1234@db:5432/namedb
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=namedb
      - POSTGRES_USER=noyon
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume: