# Generated by Django 5.1 on 2024-08-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.annotator')),
            ],
        ),
    ]
